name: Lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Python
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Install Packages
        run: poetry install --no-interaction --no-root

      - name: Run flake8
        run: poetry run flake8
